name: dynamic-linking
on: pull_request
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: [ghc884]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: nix-hs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: test/test.sh '${{ matrix.ghc }}' dynamic
