name: dynamic-linking
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: [ghc865, ghc883, ghc8101]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: nix-hs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: test/test.sh '${{ matrix.ghc }}' dynamic
